#!/bin/bash
if [[ $OSTYPE == darwin* ]]; then
  pbcopy
elif [[ $OSTYPE == cygwin* ]]; then
  cat > /dev/clipboard
else
  if command -v xclip >/dev/null 2>&1; then
    xclip -in -selection clipboard
  elif command -v xsel >/dev/null 2>&1; then
    xsel --clipboard --input
  else
    echo "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    return 1
  fi
fi

